### ISSUE TITLE
hello，I wander how to use it

### ISSUE THREAD

**Issue by vimday** [DilvanLab/SWRLVisualEditor#1]
hello，I wander how to use it

**Comment by dilvan1** [comment]
Hi,

   Orlando (CCed) is the main author, he may be able to help you.
--
Dilvan de Abreu Moreira, Ph.D.     dilvan@gmail.com
http://java.icmc.usp.br
Warning: I use a spam filter, some emails sent to me CAN be lost!

**Comment by vimday** [comment]
Hello, 
Thank you very much for your reply！ I read the readme of this document, which says it is a plugin for protege3.5. I extracted the zip file to the plugins folder under the protege folder, but it doesn't work. I want to know how to use this plugin!
